# ansible-playbook -i ',localhost' -c local dev1-generate-sealed-secrets.yml --ask-vault-pass

- hosts: all

  vars:
    namespace: "healthcare-journey-dev1"
    ocp_url: "https://sealed-secrets.apps.ocp.tst.sos.eu"

  tasks:
  - name: Clone ansible roles for sealed secrets
    git: repo=https://git.sos.eu/scm/ocppt/sealed-secrets.git
         dest=roles
         force=yes

  - name: create sealed secrets from secret
    include_role:
      name: create_sealed_secret_from_secret
    loop: "{{ secret_list }}"
    vars:
      secretname: "{{ item.secretname }}"
      inputfile: "{{ item.inputfile }}"
      secret_list:
        - { secretname: "communication-service-app-properties", inputfile: "communication-service-app-properties.yaml" }
        - { secretname: "consent-consumer-app-properties", inputfile: "consent-consumer-app-properties.yaml" }
        - { secretname: "sos-microservice-generator-app-properties", inputfile: "sos-microservice-generator-app-properties.yaml" }
        - { secretname: "case-portal-service-app-properties", inputfile: "case-portal-service-app-properties.yaml" }
        - { secretname: "teams-meetings-controller-app-properties", inputfile: "teams-meetings-controller-app-properties.yaml" }
        - { secretname: "tokenization-service-app-properties", inputfile: "tokenization-service-app-properties.yaml" }
        - { secretname: "video-meetings-consumer-app-properties", inputfile: "video-meetings-consumer-app-properties.yaml" }
        - { secretname: "myhealth-service-app-properties", inputfile: "myhealth-service-app-properties.yaml" }
        - { secretname: "drschmerzen-app-properties", inputfile: "drschmerzen-app-properties.yaml" }
        - { secretname: "application-deployment-app-properties", inputfile: "application-deployment-app-properties.yaml" }

  - name: create sealed secrets
    include_role:
      name: create_sealed_secret
    loop: "{{ secret_list }}"
    vars:
      secretname: "{{ item.secretname }}"
      secrettype: "{{ item.secrettype }}"
      inputfile: "{{ item.inputfile }}"
      appname: "{{ item.appname }}"
      targetfile: "{{ item.targetfile }}"
      secret_list:
        - { secretname: "communication-service-kerberos-ktab-secret", secrettype: "Opaque", inputfile: "rhos_dev1_com_dbo.ktab", appname: "communication-service", targetfile: "mssql.ktab" }
        - { secretname: "one-time-links-controller-kerberos-ktab-secret", secrettype: "Opaque", inputfile: "rhos_dev1_otl_dbo.ktab", appname: "one-time-links-controller", targetfile: "mssql.ktab" }
        - { secretname: "video-meetings-consumer-kerberos-ktab-secret", secrettype: "Opaque", inputfile: "rhos_dev1_vmc.ktab", appname: "video-meetings-consumer", targetfile: "mssql.ktab" }
        - { secretname: "myhealth-service-kerberos-ktab-secret", secrettype: "Opaque", inputfile: "rhos_dev1_myh_dbo.ktab", appname: "myhealth-service", targetfile: "mssql.ktab" }
        - { secretname: "case-portal-service-kerberos-ktab-secret", secrettype: "Opaque", inputfile: "rhos_dev1_cps_dbo.ktab", appname: "case-portal-service", targetfile: "mssql.ktab" }

  - name: Delete roles folder
    file:
      state: absent
      path: "roles/"
